[Feat] adding a new page for display tracks of playlist
WildCodeSchool-2024-09/JS-RemoteFR-Vendangeurs-P2-JAM-Devs pull request #64
Opened 2024-11-20 17:53 UTC by oriorinomi

2024-11-20 17:58 UTC, maximetricoche approved these changes
Coucou c'est nous, c'est Derrick, c'est ok

2024-11-20 18:09 UTC, maximetricoche requested changes

2024-11-20 18:09 UTC, maximetricoche commented on client/src/components/Playlists.tsx
>  // import carre from "../assets/icons/who.jpeg";
Il reste un code mort ici

2024-11-21 08:10 UTC, maximetricoche approved these changes
Ok

2024-11-21 08:11 UTC, jerem2802 approved these changes
ok

2024-11-21 08:16 UTC, merged